name: Static Code Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  static-analysis:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Puedes cambiar esto a la versión que necesites
        
      - name: Install dependencies
        run: npm install eslint@8.46.0
        
      - name: Config
        run: npm init @eslint/config
     
      - name: Run ESLint
        run: npx eslint 
